### ISSUE TITLE
Cannot load userPreferences

### ISSUE THREAD

**Issue by jannone** [ppeccin/WebMSX#1]
Downloaded master branch from git today and generated a release version using Grunt.
When using this version, it says that wmsx.userPreferences.load() does not exist.

**Comment by ppeccin** [comment]
Sorry, I'm preparing for the release of version 2.0, and the build scripts are currently messed up.
I will fix the release folder structure, so we can always have a stable version ready for use. I will also fix the building script for the new release.
Please check back later next Monday, we'll have an updated release folder for download.

Paulo
