### ISSUE TITLE
light C-BIOS version: Could not load file

### ISSUE THREAD

**Issue by fu-sen** [ppeccin/WebMSX#108]
I have been using a **light C-BIOS version** for some time,
but It no longer works with URLs that include files.

https://webmsx.org/cbios/?ROM=https://msx-jp.balloon.net.eu.org/balloons.rom
https://webmsx.org/cbios/?MACHINE=MSX2PJ&ROM=https://msx-jp.balloon.net.eu.org/yjk.rom
display **Cou;d not load file: (URL)  Error: 0** doesn't work

The rom file has been around for a while and the regular version works fine.
https://webmsx.org/?ROM=https://msx-jp.balloon.net.eu.org/balloons.rom
https://webmsx.org/?MACHINE=MSX2PJ&ROM=https://msx-jp.balloon.net.eu.org/yjk.rom

**Comment by ppeccin** [comment]
Fixed on 6.0.5
