### ISSUE TITLE
Can BASIC_BLOAD and BASIC_BRUN be added?

### ISSUE THREAD

**Issue by digitalica** [ppeccin/WebMSX#11]
we have some binary files on the disks that should be bloaded and run. Most importantly MemMan (but that would like MSXDOS as well, a different issue ;-) )

BASIC_BLOAD could do BLOAD ""    (not needed now, but makes things consistent  i think)
BASIC_BRUN could do BLOAD "",r   (that is needed)

We could use BASIC_ENTER of course, but the above would be more clean I think...

**Comment by oh-ren** [comment]
I'm not sure if the number of use cases justify this? BASIC_ENTER is sufficient perhaps.

**Comment by digitalica** [comment]
BASIC_LOAD works fine for me, ive been using it, and have not seen any issues.

I kind of like the params idea.

**Comment by ppeccin** [comment]
Good ideas. I will consider all these options for the next release.

**Comment by ppeccin** [comment]
Added BRUN and BLOAD. Will publish a new release tomorrow.
