### ISSUE TITLE
BASIC_ENTER doesn't seem to work?

### ISSUE THREAD

**Issue by digitalica** [ppeccin/WebMSX#12]
I try

```
http://webmsx.org/?BASIC_ENTER=print%20%22hoi%22
```
expecting to have the print statement executed, but it I end up in an emulator just showing OK promt... Am i missing something?

**Comment by ppeccin** [comment]
Yes, it should execute the command...
I will have to take a deeper look into this.
Thanks for the report.

**Comment by digitalica** [comment]
thanks. So it's not that i'm missing something simple :-( The console log doesn't tell me much. I may be able to have a better look at the code later. At first glance it looks ok. 

I was trying this to work around request #11 of course ;-)

**Comment by ppeccin** [comment]
Nasty regression bug...
I'm fixing this and adding BRUN and BLOAD. Will publish a new release tomorrow.
Thanks
