### ISSUE TITLE
Allow starting with Ctrl (from URL) to free more memory

### ISSUE THREAD

**Issue by digitalica** [ppeccin/WebMSX#14]
for example:

http://webmsx.org/?MACHINE=MSX1E&DISKA_FILES_URL=http://www.msxcomputermagazine.nl/archief/diskzips/mcmd16.zip&BASIC_RUN=hal

shows an out of memory. It requires the real MSX to boot with Ctrl pressed. If i remember correctly that enabled only 1 diskdrive. 

Is there a way to simulate that on WebMSX?

**Comment by ppeccin** [comment]
No, not in the current version. Sorry!
I can think of something, but it will take some work.

Paulo

**Comment by digitalica** [comment]
Thanks, and no hurry:  for the msxcomputermagazine.nl project the majority of the software runs fine, and adding BASIC_BRUN made it even better ;-)

**Comment by digitalica** [comment]
I did found another example program, that actually tells the user Ctrl should be pressed on boot ;-)

http://webmsx.org/?MACHINE=MSX2E&DISKA_URL=http://www.msxcomputermagazine.nl/archief/disks/mccm/disk59b.di2

(in a rather blunt way, but it was probably effective at the time)

Also, i realised this could be fixed together with issue #9, where the approach could be to allow 'Shift' to be pressed on startup.

**Comment by TFHFony** [comment]
Yep, this would be a request from my side as well :) Would be nice if it were added to a new future version.

**Comment by ppeccin** [comment]
Implemented for the next Release 5.0
