### ISSUE TITLE
Japanese keyboard support

### ISSUE THREAD

**Issue by yandod** [ppeccin/WebMSX#18]
some games require Japanese keyboard. and how can we add that configuration?

**Comment by ppeccin** [comment]
Can you explain it a little further?
What you need exactly? Are you talking about KANJI support, or is it a keyboard layout issue?

**Comment by yandod** [comment]
yes, I was talking about keyboard layout.

And I found this. I will start from here.
https://github.com/ppeccin/WebMSX/blob/b8b42518d9ddbf65cfdbe2d85ba034fb6e4b304b/src/main/room/controls/BuiltInKeyboards.js

**Comment by yandod** [comment]
now I realize how this works as is.
<img width="665" alt="webmsx" src="https://cloud.githubusercontent.com/assets/103903/23861279/e72742e4-084c-11e7-9a90-a13c3822406c.png">

**Comment by ppeccin** [comment]
Maybe you just need to start a Japanese machine!
Or maybe you need to activate the KANJI extension if using an Euro/American
machine.
All this is configurable in the Settings menu, and does not need any
specific keyboard configuration.

There is also the KEYBOARD_JAPAN_LAYOUT parameter that lets you choose
between ANSI (0) and JIS (1) layouts.

Is that what you're looking for? Does that solve your problem?

Paulo

**Comment by yandod** [comment]
yes. those are technically okay.
I may write down some step to use Japanese characters somewhere.

having Japanese keymap image on setting tab might be plus. but it is just a nice to have.

**Comment by yandod** [comment]
Thanks!
