### ISSUE TITLE
PSG emulation could be improved

### ISSUE THREAD

**Issue by oh-ren** [ppeccin/WebMSX#2]
Check e.g. the [bold demo](http://vik.cc/dvik-joyrex/demos.html) or [IO](http://www.pouet.net/prod.php?which=65232).
Also noticeable in the boomerang sound in Livingstone Supongo.

**Comment by ppeccin** [comment]
I notice that too, but I have no idea what could be causing this. Maybe with some more knowledge of what exactly those demos are doing? Do you have any idea what could be the problem?

**Comment by oh-ren** [comment]
Nope, this stuff is (way) out of my league... ;-)

I reckon you wrote the PSG emulation from scratch (from (official) documentation), like everything or most else?
Maybe something can be learned from other implementations?

It does seem there are slight differences in playback between e.g. blueMSX & openMSX as well.

**Comment by ppeccin** [comment]
Last night I had an insight on how to improve the PSG emulation, specially in those cases you mentioned. It wasn't while I was looking at the code, nor reading other implementations...

I was watching a demo video about a Yamaha Musical Keyboard... Then I heard the word "detune"....  :-)

Then I realized I was doing some optimizations in the PSG emulations to gain speed, but that can ruin some effects composers may want to achieve. The optimization can make 2 channels of sound become "out of sync", which is not a problem in "normal" conditions, but may be a problem in other situations where the composer intended to be make 2 channels in sync but just a little out of phase or with a very little difference in frequency.

I already made some tests, and if I remove the optimization, it seems to work great can make a very big difference in IO and BOLD.

Thanks for the push...  ;-)

**Comment by oh-ren** [comment]
Hey, cool story! :)
Glad my report seemed to be use-/helpful, looking forward to the commit..! ;-)

**Comment by oh-ren** [comment]
Hey, checked it out, sounds better indeed!
Boomerang in Livingstone still doesn't sound as it should though, but I reckon there are bigger concerns.. :) (Plus, there are even differences between the big 2 here..)

Thanks!

**Comment by ppeccin** [comment]
Hey, where can I find this game for testing?
Is it MSX1 or MSX2?

Thanks

**Comment by oh-ren** [comment]
Both :) But try the MSX1 version. http://www.msxgamesworld.com/

**Comment by ppeccin** [comment]
I saw a video of the gameplay on youtube, and the boomerang sound "sounded"
the same as in WMSX for me...
Is it supposed to make some noise while travelling, or just at launch?

**Comment by oh-ren** [comment]
Did you see [this](https://www.youtube.com/watch?v=PckbhzSEyOY&t=18s)?
That's how it sounds like in openMSX. The sounds seems to start out right in WMSX, but it ends with a strange 'beep' like tone (not quite sure how to describe it.. ;)) The ending of the sound is also clearly noticeable in blueMSX (though sounding authentic to me), less so in openMSX. OpenMSX seems to 'cut out' earlier..(?)

**Comment by ppeccin** [comment]
Well, its kinda subtle. I don't have an idea right now what may be going wrong.
To fix that it will require another epiphany!

**Comment by oh-ren** [comment]
:) I'll close this for now, thanks :)
