### ISSUE TITLE
Unlimited Sprite Option

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#22]
Make it possible to set the unlmited sprite options by arguments.

**Comment by ppeccin** [comment]
Well, its a nice idea, but the Sprite modes on WebMSX are considered "debugging" modes, sine they change the hardware behavior away from the spec. I'm not sure if the correct emulation will be guaranteed with any of the debug modes engaged.
But yes, I can add the corresponding URL parameters for all the debug modes!

**Comment by TFHFony** [comment]
Well, it would be nice. You can include a warning in the manual of course :)

**Comment by oh-ren** [comment]
According to the [corresponding bit](http://openmsx.org/manual/commands.html#limitsprites) in the openMSX manual. Apparently some games **do** rely on the limitation. (Would be interesting to assess which (popular) games exactly.. ;))

**Comment by TFHFony** [comment]
The default setting should be with the normal limitations of course :)

**Comment by ppeccin** [comment]
Feature implemented for the next release.
