### ISSUE TITLE
PSG emulation sometimes off

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#25]
I've noticed that the PSG emulation is sometimes off or incorrect. Two games that show this very well:

http://www.file-hunter.com/MSX/index.php?id=alibaba
Here the music is just off. The original game seems to play with the pitch of the notes a bit, generation a more eastern note-set.

http://www.file-hunter.com/MSX/index.php?id=chuckieegg
In this game, after the welcome noise, the PSG just goes crazy. I've tested about 10 versions in WebMSX and they all have the same problem, while functioning OK in multiple OpenMSX configurations.

Both games do display a warning in OpenMSX that they show behaviour which could damage the PSG in old systems. Maybe the PSG emulated in WebMSX is of that "older" type?

**Comment by oh-ren** [comment]
Related: #2

**Comment by ppeccin** [comment]
Hum... Interesting. I don't have any idea right now what could be the issue.
But I will do some tests about that when I start working for the next release.

**Comment by TFHFony** [comment]
Maybe usefull for testing: Another game that really has sound issues on WebMSX:
http://www.planetemu.net/rom/msx-various-dsk/thing-bounces-back-1987-gremlin-graphics-software-3

**Comment by TFHFony** [comment]
This problem seems to be solved now :)

**Comment by ppeccin** [comment]
Really?  :-)
