### ISSUE TITLE
Matra games don't run correctly

### ISSUE THREAD

**Issue by sdsnatcher** [ppeccin/WebMSX#29]
The games produced by Matra do not run correctly on WebMSX. Some freeze, others lack part of the bottom of the screen.

**Comment by TFHFony** [comment]
The Sex Bomb Bunny demo even freezes at the welcome screen.

**Comment by ppeccin** [comment]
Can you guys list the games having problems please?
Do these Matra games have anything special that you know of?
Any ideas why they don't work?

Thanks

**Comment by TFHFony** [comment]
I don't know about the other Matra games, but I know thw Sex Bomb Bunny uses an overscan modus, which also ticks off OpenMSX (The screen flickers like crazy, making the game unplayable). I don't know if this is also the cause of the game freezing in WebMSX.

This is the version I tested with:

http://www.planetemu.net/rom/msx-msx2-various-dsk/sex-bomb-bunny-demo-2000-matra

**Comment by ppeccin** [comment]
They do now!
Please try again in the current release (5.3)!

Thanks

**Comment by TFHFony** [comment]
Indeed.... They work fine now:

https://www.file-hunter.com/MSX/index.php?id=sexbombbunny

**Comment by TFHFony** [comment]
Time to close this "issue" :)
