### ISSUE TITLE
Loading a state resets the sprites mode

### ISSUE THREAD

**Issue by rdlmda** [ppeccin/WebMSX#34]
WebMSX: 5.0.4
Browser: Firefox 54.0
OS: Fedora 24

Steps to reproduce: Load [this state file](https://github.com/ppeccin/WebMSX/files/2064554/WMSX.SaveState.wst.zip). Set sprites mode to "both". Save the state either as a file or internally. Load the newly saved state. Sprites mode is set to "normal" again.

**Comment by ppeccin** [comment]
Fixed for next release (5.3)
