### ISSUE TITLE
perhaps i found a bug from a game i made

### ISSUE THREAD

**Issue by ghost** [ppeccin/WebMSX#35]
i can’t open this game (made by me) http://webmsx.org/?ROM=http://nitrofurano.altervista.org/retrocoding/msx/roms/libreway.rom (it works fine with other games i have in the same altervista directory) 
while i can from https://www.file-hunter.com/MSXdev/index.php?id=libreway - can someone let me know what i’m doing wrong?

**Comment by nitrofurano** [comment]
i think i have it fixed

**Comment by ppeccin** [comment]
What problem were you having?
How did you fix it?

Regards,
Paulo
