### ISSUE TITLE
No sound iOS 

### ISSUE THREAD

**Issue by hfortuin** [ppeccin/WebMSX#39]
Hi

I have been using webmsx for a few days on my iPad. I noticed today that sound stopped working. Is this a known issue?

**Comment by ppeccin** [comment]
No... Not that I'm aware of...
Also, there were no version updates on the official website for more than a
month.
Did you update anything on your browser/OS? Does the same problem occur in
Safari and also in Chrome?

Sound should start from the moment you open the emulator, or maybe only
after the first interaction with the interface (any tap, touch or click).

Paulo

**Comment by hfortuin** [comment]
Hi

It appears to be working again. I did not have sound on my iPhone and iPad,
but after fiddling with some settings on the iPad/iPhone and reloading a
"saved state" I got it to work again. I am not sure what caused the issue.
I hadn't updated my iPad, I just hadn't touched it for a few days and all
of a sudden I did not have sound anymore.

Regards

Hein

**Comment by ppeccin** [comment]
Tell me, are you using the emulator in standalone mode (Icon added to
Desktop), or directly on the website, in which case, what browser?

Paulo

**Comment by hfortuin** [comment]
Hi

I was using the emulator in standalone mode and directly on the website. In
the latter case I was using Safari (ios version 11.4.1). Audio on iPad
seems to be different than on iPhone. On iPad I need to wear headphones,
iPhone just plays sound via the speaker (provided mute is turned off).

Hope this helps.

Regards

Hein

**Comment by ppeccin** [comment]
Only on headphones??? That'a totally strange and the first time I head this!
The emulator has absolutely no control whether sound should come from the
speakers or only from headphones. It must be some setting on your device,
or maybe a bug on the iOS/Safari.

I have an iPad, and sound on WebMSX works just fine for me, I could not
reproduce this issue. Restarting the app does not fix the problem?

Sometimes I randomly get sound issues (no sound) on my iPad, using normal
native apps. Sometimes I just have to restart the app, or maybe even
restart the iPad...
