### ISSUE TITLE
Wrong drive allocation when connecting a DSK image to a machine with internal disk ROM

### ISSUE THREAD

**Issue by Wierzbowsky** [ppeccin/WebMSX#44]
I observed the wrong drive allocation when connecting a DSK image to a machine with internal disk ROM in the SubROM. The connected disk image becomes C: instead of A:

Example URL where my DSK image becomes C: drive after booting, disks A: and B: are offline:
https://webmsx.org/?BIOS_URL=http://www.podrezov.com/webmsx/yis805.rom&BIOSEXT_URL=http://www.podrezov.com/webmsx/yis805sub.rom&P=RAM128,NOMSXMUSIC&DISKA_URL=http://www.podrezov.com/webmsx/prog1.dsk

Machine configuration:
https://www.msx.org/wiki/Yamaha_YIS-805

**Comment by ppeccin** [comment]
Will be addressed in #43
