### ISSUE TITLE
Wrong RAM allocation for Yamaha MSX2 machines with external BIOS

### ISSUE THREAD

**Issue by Wierzbowsky** [ppeccin/WebMSX#45]
The RAM is allocated in subslot 3.0 instead of 3.2 for the Yamaha MSX2 machines. There should be a way to specify the RAM location in the settings because a lot of software assumes that RAM is in 3.2 and won't work if RAM is in a different subslot. Example URL showing the wrong RAM subslot allocation:

https://webmsx.org/?BIOS_URL=http://www.podrezov.com/webmsx/yis805.rom&BIOSEXT_URL=http://www.podrezov.com/webmsx/yis805sub.rom&P=RAM128,NOMSXMUSIC&CARTRIDGE1_URL=http://www.podrezov.com/webmsx/TESTRAM.ROM

Default Yamaha YIS805 machine slot configuration:
https://www.msx.org/wiki/Yamaha_YIS-805

**Comment by ppeccin** [comment]
Will be addressed in #43
