### ISSUE TITLE
Media is not mounted correctly when external BIOS and SubROM are used

### ISSUE THREAD

**Issue by Wierzbowsky** [ppeccin/WebMSX#46]
Media is not mounted correctly when external BIOS and SubROM are used. When the media is mounted, the new drive is not created and all available drives in a system always return "Disk offline" error.

Example of mounted media not working with external BIOS and SubROM:
https://webmsx.org/?BIOS_URL=http://www.podrezov.com/webmsx/yis805.rom&BIOSEXT_URL=http://www.podrezov.com/webmsx/yis805sub.rom&P=RAM128,NOMSXMUSIC?DISK_FILES=https://wiki.yola.ru/_media/msx2scrn.bas&BASIC_RUN=msx2scrn.bas

Without the external BIOS and SubROM this works:
http://webmsx.org/?DISK_FILES=https://wiki.yola.ru/_media/msx2scrn.bas&BASIC_RUN=msx2scrn.bas

Please fix, thanks.

**Comment by ppeccin** [comment]
Will be addressed in #43
