### ISSUE TITLE
Full Screen doesn't work 100% in Edge

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#47]
When going full screen in Microsoft Edge, sometimes a part of the browser doesn't go away. My own page is a very good example:

https://www.file-hunter.com/MSX/

WIll show this in Edge when going Full Screen:
![FullSreen](https://user-images.githubusercontent.com/28051172/65681892-23929c00-e05a-11e9-89dd-56c01cac3b25.png)

**Comment by ppeccin** [comment]
Well... You know, officially WebMSX does not yet support Edge. I still have
to test some issues (like this one) and check if it is even possible to fix.

It probably hast something to do with the Javascript Full Screen API
support still lacking on Edge, or something in your layout that prevents it
from going full screen.
Do you use frames or something similar in your layout?

If  WebMSX can't really go full screen, it only tries to dominate all the
space on its container element.
Things like position: fixed elements, or elements with absolute position
and hardcoded z-indexes, can completely mess with this "semi" full-screen
layout.

It can get complicated, I can only tell by looking deep on the design/CSS
of your page, while asking why Edge is failing....

Paulo

**Comment by TFHFony** [comment]
Well... The points you mention are very close.
The menu on the left and the menubar at the top are hardcoded through the following .CSS:
`        #leftCol {
            position: fixed;
            width: 272px;
            background-color: #000;
            font-size: 21px;
            overflow-y: scroll;
			overflow-x: hidden;
            top: 0;
            bottom: 0;
            margin-top: 98px;
        }

        #content {
            position: relative;
            margin-left: 276px;
            margin-top: 150px;
        }`

So I guess that's what messing with the fullscreen lay-out in Edge.

**Comment by TFHFony** [comment]
Come to think of it, isn't Microsoft migrating Edge to a chromium engine soon?

**Comment by ppeccin** [comment]
That would be wonderful!   :-)

**Comment by TFHFony** [comment]
OK, good news. I just downloaded the Edge Beta from the Insider area: WebMSX goes full-screen without any problem!

**Comment by ppeccin** [comment]
Good news indeed!  :-)

**Comment by TFHFony** [comment]
Edge with the Chomium engine has been released last January and guess what: Full screen works fine in this new version!
