### ISSUE TITLE
Cannot load files with spaces on their names

### ISSUE THREAD

**Issue by Konamito** [ppeccin/WebMSX#5]
I've tried to load some files using JavaScript and I have noticed that the emulator fails to load them. I get a 404 not found error:

> Could not load file(s):
> 
> No valid ROM, Cassette or Disk found.

Here's an example of one of my files: _Andorogynus (Telenet Japan, 1987).zip_

**Comment by ppeccin** [comment]
The problem is the comma ",", not the spaces. It was being used as a special file name divider character. Switched to ":" instead of ",".
Please update!
