### ISSUE TITLE
Labirint game: sprite collision falsely detected

### ISSUE THREAD

**Issue by mr-GreyWolf** [ppeccin/WebMSX#50]
Please read this topic:
[Labirint game: sprite collision falsely detected #1198](https://github.com/openMSX/openMSX/issues/1198)

**Comment by ppeccin** [comment]
Hum... Interesting...
I'll check on that and probably fix for the 6.0 release.

Thanks

**Comment by ppeccin** [comment]
Fixed in v6.0.0
