### ISSUE TITLE
Loading tape from local filesystem

### ISSUE THREAD

**Issue by msx80** [ppeccin/WebMSX#53]
Hi, i'm trying to launch WebMsx like a regular "offline emulator", by running chrome from the command like, calling the "embedded" release and passing it a tape and other configurations.

The launcher i came up with is the following:

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files --start-fullscreen "file:///C:/Users/xxx/dev/WebMSX/release/stable/5.4/embedded/index.html?SCREEN_FULLSCREEN_MODE=1&TAPE=file%3A%2F%2F%2FC%3A%2FUsers%2Fxxx%2Fdev%2FWebMSX%2Frelease%2Fstable%2F5.4%2Fembedded%2Fcaduta_massi.cas"`

It all works except i cannot load the tape from the config option. First error i get is obviously "blocked by CORS policy", but the  `--allow-file-access-from-files` parameter should bypass that. And indeed i don't get the CORS error anymore on the console, but i still have WebMSX giving error:

wmsx: Reading file from: file:///C:/Users/xxx/dev/WebMSX/release/stable/5.4/embedded/caduta_massi.cas
wmsx.js:352 Could not load file: file:///C:/Users/xxx/dev/WebMSX/release/stable/5.4/embedded/caduta_massi.cas
Error: 0 

Any idea on how to bypass that ?

**Comment by ppeccin** [comment]
Fixed on Release 5.4.1.

[https://github.com/ppeccin/WebMSX/releases/tag/v5.4.1](url)
