### ISSUE TITLE
CPU Turbo modes don't function

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#54]
I have added Illusion City to my site, but it keeps nagging me about the fact that that machine I have set is not running in Turbo mode. When I set the CPU to 4x speed through the Quick Options menu the CPU 4x appears and all works fine. But no matter which option I use:

 'CPU_SOFT_TURBO_MULTI' => 4,
 'CPU_TURBO_MODE' => 4,
 'Z80_SOFT_TURBO_MULTI' => 4,
 'Z80_CLOCK_MODE' => 4

The CPU x4 doesn't appear and the software seems to keep running on 3,57Mhz.
In the past the  'CPU_TURBO_MODE' => 4, seemed to work fine. I have added the files and the webpage is: https://www.file-hunter.com/MSX/index.php?id=illusioncity
I hope you can find out what I am doing wrong here.

**Comment by TFHFony** [comment]
Additional: Setting the machine to MSX2PPA does give 4 x CPU Speed.

**Comment by ppeccin** [comment]
Well, isn't that game Turbo R only? Maybe its checking for the "real" R800
mode or machine type. Setting the normal Z80 turbo even to 8x will not
satisfy the requirements!
You will have to wait for Release 6.0 to get real Turbo R functions.

Regardless, the turbo setting parameters should be working. I will check
them.
For now, try using the URL syntax, like:

http://webmsx.org/?CPU_TURBO_MODE=4

Regards

**Comment by TFHFony** [comment]
Hi Paulo,

The game doesn't have any R800 code. It's only Turbo-R because of the speed it requires. Setting the CPU Turbo to 4x through the quick options menu makes the message disappear.
I've also tried older games on my site which have the CPU_TURBO_MODE=1 function but these also are running at 3.57Mhz at the moment. Only setting the MSX2PPA will force the CPU to 4x.
I'm quite sure the function isn't working correctly in 5.4.0.

As for the temporary solution: It's not useable for the current setup of my site :)

**Comment by TFHFony** [comment]
Hi Paulo,
I guess this has to do with the reported issue:
https://github.com/ppeccin/WebMSX/commit/3be4e20a5d97ec3aac3494fd540ceade0480bc60

**Comment by ppeccin** [comment]
Exactly...

**Comment by ppeccin** [comment]
Hi.
We have a solution to this problem in the new Release 5.4.4

But for some time it requires the use of a new form of parameter overriding
for those settings that get changed by the Machine Type configuration.

Now you can override any parameter by setting the value against the
WMSX.params object, instead of WMSX directly. Those will be treated just
like URL parameters.
Sp for example:

WMSX.params.CPU_TURBO_MODE = 4;

Also, are you using the MSX2++ machines? They will be removed on the next
major release, in favor of the TurboR.

If you still need similar behavior for non-TurboR machines, we now have a
new "BOOSTED" Preset. It will produce similar effects on any Machine Type

Please let me know if this works for you!

Regards,
Paulo

**Comment by TFHFony** [comment]
Hi Paulo,

This solution should work fine for me. I tried downloading 5.4.4 though,
but files I received still contains wmsx.js v5.4.0, although the date was
set to 03-01-2020. Could it be that something went wrong?
As for the MSX2++ machines: I have 4 of these, but I can easily change them
with the new release. As long as I know it beforehand it should be fine!

Kind regards!

Arnaud

**Comment by TFHFony** [comment]
Hi Paolo,
The archive from Github still serves 5.4.0, but... I have converted your webmsx.org page to a wmsx.js file to do some testing, but... It still doesn't seem to work. Righ now I set the following:

WMSX.AUTO_POWER_ON_DELAY = 0
WMSX.DISKA_URL = "games/IllusionCity.zip";
WMSX.PARAMS.CPU_TURBO_MODE = 4;
WMSX.MACHINE = "MSX2PA";

but the CPU speed doesn't change. I will send you a non-public link by e-mail so you can see it live as well.

Regards!

**Comment by ppeccin** [comment]
Hi,

The wrong file is because from now on minor and bug fix releases are on a
different branch on Github.
Be sure to select the v5.4 branch, or use the Releases tab, which is easier
and more correct. You shouldn't never get "trunk" files anymore, only
releases.

About the parameter settings, note that it is WMSX.params... Lower case.


Regards

**Comment by TFHFony** [comment]
Aha... Lower case.
This means I will have to take a look at the code rendering on my website:
As all previous settings were uppercase, it's currently converting
everything to uppercase..

**Comment by TFHFony** [comment]
I think I've found a quick for my site. I'll have a look this evening!

Op za 4 jan. 2020 17:07 schreef Arnaud de Klerk <arnaud@file-hunter.com>:

> Aha... Lower case.
> This means I will have to take a look at the code rendering on my website:
> As all previous settings were uppercase, it's currently converting
> everything to uppercase..
>

**Comment by TFHFony** [comment]
OK, I've removed the upper case conversion and checked if all the current arguments were uppercase manually. Now I can add the params argument in lower case and indeed.... It works again:

https://www.file-hunter.com/MSX/index.php?id=illusioncity

Were there any other arguments affected by this bug except for the CPU speed? I might have to check some other games/programms on my site as well :)

**Comment by ppeccin** [comment]
No, only this one. And this is temporary.
On Release 6.0 it will all be gone.

**Comment by TFHFony** [comment]
OK... For the moment I've kept a copy of my original code as well. When 6.0
comes out, I will update the code accordingly :) :)
Thanks for your help and solving the bug! I hope it didn't take to much
time from your 6.0 development. I'm really looking forward to it.
And if you want to, you can close this this issue now :)

**Comment by ppeccin** [comment]
No problem! Thanks for pointing this bug.
