### ISSUE TITLE
Not all statefiles work correctly

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#55]
Not all statefiles work the same anymore. For example this one hangs the machine completely: 
https://www.file-hunter.com/MSX/games/File-Hunter.zip

The normal behaviour would be displaying my altered BASIC welcome (Just a bunch of print commands) followed by a reset (defusr=0:a=usr(0).

For the rest: Great Update!

**Comment by ppeccin** [comment]
Hum... I don't know why, no errors occur when I load the state, just
machine hang.

What software do you load? What does it do?
Does it work if you not use the savestate and load it from scratch?
Can you send me the software?

Peccin

**Comment by ppeccin** [comment]
Also, how did you create this savestate? Is is too old?
The contents of the state is very strange. It has several slots duplicated,
like 2 BIOS Exstensions, 2 MSX-MUSIC and 2 DiskROMs.

Maybe on the previous release, you loaded a very old state, them saved it
again?
Something seems to have corrupted this savestate.

Paulo

**Comment by ppeccin** [comment]
Also, I tried to load this state with versions 5.4 and 5.3, and it also
hangs or resets the machine.
Are you sure this state you sent me is correct? On which version did it
work for you????
Are you having problems with other states as well?

Paulo

**Comment by ppeccin** [comment]
Oh, just now I noticed you said the reset is expected...
I'll continue investigating...

Paulo

**Comment by TFHFony** [comment]
The reset is indeed expected. I made this statefile some time ago after you updated WebMSX with the function to create smaller savestates. The program it's running is actually very simple:

10 CLS
20 PRINT"FILE-HUNTER.COM version 4.0
30 PRINT"Copyright 1999 by TFH|Fony
40 PRINT"28815 Bytes free
50 PRINT"Ok
60 PRINT"10 ' *******************************
70 PRINT"20 ' *  WWW.FILE-HUNTER.COM RULEZ  *
80 PRINT"30 ' *     and ( . ) ( . ) too     *
90 PRINT"40 ' *******************************
100 PRINT"Ok"
110 PRINT CHR$(219)
120 FORA=0TO2500:NEXT
130 DEFUSR=0:PRINTUSR(0)

And I made the savestate right after running it. I've checked my other savestates. These all seem to work. I will create a new savestate for my site. If you want, you can investigate further. On the other hand: I don't think it's a big issue. I can create a new save-state easily :)

**Comment by ppeccin** [comment]
Yes, go on and fix it.
Please send me the new savestate, ok?

I'll investigate a little more, because that is not supposed to happen, and
can show a hidden bug...

Thanks!

**Comment by TFHFony** [comment]
Well, the new one has been made and I've replaced the old one:
https://www.file-hunter.com/MSX/games/File-Hunter.zip

**Comment by ppeccin** [comment]
Hi,

Just to let you know I release v6.0.1 with some fixes, one is important to
you.
Please update!

Paulo

**Comment by TFHFony** [comment]
Hi Paolo,

Thanks! I will download it and update it today. Thanks for your work!

Arnaud
