### ISSUE TITLE
Ingame music issues

### ISSUE THREAD

**Issue by tluyben** [ppeccin/WebMSX#7]
In game music sounds awful; I guess that is my setup; Ubuntu linux with Chrome. But any idea why it happens as video sound + browser game sound for non webmsx stuff sounds great. When I am running something like Metal Gear 1, Chrome pulls a consistent 50% CPU in top; not more not less.

**Comment by tluyben** [comment]
Tried under Firefox under Ubuntu; sound is perfect there; SCC, SCC+ & PSG all sound spot on... So some Chrome issue, at least under Linux.

**Comment by tluyben** [comment]
On Android Chrome has the same behavior: distorted sound while everything else seems fine under Chrome.

**Comment by ppeccin** [comment]
Well, I did not do much testing in Linux, but it should work normally. What is your machine's config?

In Android I know there is some issue in Chrome impl. of the WebAudio API. Maybe its the sema issue affecting Chrome on Linux. There is not much we could do... I already opened a bug in Chrome's website. You may try to increase the audio buffer size, but that will introduce lag and may not solve the problem.

I am currently working on a better interface for mobile devices. Then we will have more testing on those devices.

**Comment by tluyben** [comment]
Thanks, If I can help testing or with anything else, just ask.
