### ISSUE TITLE
Support multiple partitions hard disk

### ISSUE THREAD

**Issue by ytsejam78** [ppeccin/WebMSX#71]
WebMSX supports hard disk with one partition and it is very easy to create. I tried creating a blank disk, adding MSXDOS.SYS and COMMAND.COM and bingo! A booting hard disk with MSX-DOS 1 image.
But MSX-DOS can handle up to four partitions for disk controller (drives A,B,C,D if only one disk controller present).
Is this something that the current hard disk interface emulation could support?

**Comment by ppeccin** [comment]
Hi!

WebMSX supports 2 physical Floppy drives and 1 physical HardDisk device
using Nextor, but it does not put any constraints on the number of logical
devices.
You can, for instance, use the FDISK utility included in Nextor to
partition your HardDisk image as you need.

Launch the FDISK utility from BASIC with: CALL FDISK

One other different thing is the built-in image creation tool included on
WebMSX. That one supports automatic creation of 16, 32. 64 and 128MB disks,
with or without system boot files (you don't need to copy them yourself),
and will automatically add one single partition taking the entire space.
But even with this you can use FDISK after the image is created and
re-partition it as you like.

Paulo

**Comment by ytsejam78** [comment]
I see... I need to boot Nextor from floppy with fdisk and re-partition the hard disk.
Thanks for the help Paulo, I will let you know if it works!

**Comment by ytsejam78** [comment]
Ok I didn't need to boot from floppy - I now understand what you mentioned about NextorBasic CALL FISK.
I was able to create four 32M partitions on a 128M blank disk.
However, when I want to access another drive different from the boot drive, I get: "Bad drive name".
I am going to make a few more tests just in case I did something wrong, maybe try with smaller partitions and let you know. Thanks.

**Comment by ytsejam78** [comment]
Paulo, thanks for your help again. Almost there.
Here's what I am doing:
Using MSX2+ America machine with Hard Drive and RAM mapper.

1. Add new blank 128MB disk
2. Power on (reset)
3. From NextorBasic: CALL FDISK
4. Select driver, hard disk, logical unit (1, 1, 1)
5. Delete all partitions (D)
6. Add four 32M partitions (P, 32, A, A, A)
7. Write partitions to disk (W)
8. Reset
9. Download dsk with "Save disk image"
10. Using DiskExplorer for Windows, add MSXDOS.SYS and COMMAND.COM to first partition
11. Remove and load disk again
12. Reset (successfully boots into MSX-DOS drive A:)
13. Try to switch to B: and get "Invalid drive"

Alternatively tried FILES"B:" from NextorBasic and get "Bad drive name"

**Comment by ppeccin** [comment]
That is normal Nextor behavior.
It automatically mounts only the FIRST partition from each device to a
drive letter. So you get A:, but will not get the other 3 partitions
mounted automatically,

You have to mount other partitions that you want with the MAPDRV util.
For example, in BASIC:

CALL MAPDRV("D:", 2, 1, 0)

Will mount partition 2 of device 1 from interface 0 to drive D:
You can then check your drive letters with: CALL DRVINFO

You can also define automatic partition mounting through a file located on
the first partition.

Please, take a look at the Nextor docs to learn about these utilities and
behaviors.

Also, you don't have to use external utilities to add files to your drives
on WebMSX.
You can simply drag and drop the files to the "+FILE" area on the target
drive, or use the "Import Files to Disk" function on the drive menu.

Paulo

**Comment by ytsejam78** [comment]
Hi Paulo, as you can see I am a newbie on Nextor stuff.
Your help is more than enough, thanks.
I will read NextorBasic docs and play with it.
I am used to standard Disk Basic / MSX-DOS because I own a Beer IDE interface and partitions are automatically mounted with that configuration.
Maybe it would be nice if at some point WebMSX can emulate different disk interfaces... but I understand that is one major feature request... I will focus on learning how to use Nextor for the time being.
My aim is to try a game collection I built on a compact flash card (which due to limitations of MSX-DOS 1.x uses more than one partition) on WebMSX... just for fun!

Cheers,
Mariano

**Comment by ytsejam78** [comment]
Hi Paulo,
Just to let you know I got it to work!
:)

**Comment by ppeccin** [comment]
Nice! :-)
