### ISSUE TITLE
WebMSX stopped working on Chrome

### ISSUE THREAD

**Issue by robertocapuano** [ppeccin/WebMSX#77]
After a recent update of Chrome on macOS WebMSX doesn't render screen output but only a black screen.

![Screenshot 2021-10-06 at 07 59 42](https://user-images.githubusercontent.com/2651123/136148543-77d4dba6-ac5e-4a4c-a066-87219e38ac65.png)

Console shows some error messages:

![Screenshot 2021-10-06 at 08 01 35](https://user-images.githubusercontent.com/2651123/136148748-6d5ce507-7fae-4397-a319-f2ec85887ee8.png)

**Comment by jannone** [comment]
That's odd. I'm on a Mac and still works for me.
Mac OS 11.6 (Big Sur)
Chrome Version 94.0.4606.71 (Official Build) (x86_64)

Could it be a Chrome extension getting in the way?

**Comment by robertocapuano** [comment]
Just now a new version of Chrome (94.0.4606.81) fixes the issue: WebMSX works fine.
Sorry for the inconvenience.
--
r.
