### ISSUE TITLE
cant type quotes

### ISSUE THREAD

**Issue by digitalica** [ppeccin/WebMSX#8]
i cant type (double) quotes in de emulator, using my US keyboard. Using F2 (cload") and backspace is a workaround, but not a good one ;-)

changing keyboard type (alt-l) doesn't help.

same issue with `  ~ ^ ' " .... i think its related to the fact my ubuntu OS uses them as dead keys to allow combining them with letters like ö, so to get the quote i type quote / space: ". 

can others type qoutes? is this issue known? If not i'll have a look in the code, see if i can find the cause and maybe fix it.

**Comment by ppeccin** [comment]
Hi...

Did you try to customize your keyboard keys in the Settings Dialog?
That may solve the issue, or at least you can try to map some other physical key to the ones you need.
My Windows also use them as dead keys and I have no problem.

If that is your Operating System not reporting the key events to the browser, it may be impossible to solve, besides mapping them to other physical keys.

**Comment by digitalica** [comment]
I was using the stock Firefox in Ubuntu 16.04.

I didn't see the option to customize the keyboard before....
Managed to configure ' (dead key single quote) to be 'dead#0, space', so i can type single quote. But then I loose the mapping for spacebar :-(
Did not manage to do the same for the " (double quote), as because it requires shift.

Also the ` key (at the top left, the backtick) shows the same 'dead#0' code. So i can't distinquish between both dead keys. Used http://unixpapa.com/js/testkey.html to check: same result, no difference. Googling on how to handle dead keys in javascript gave little useful result :-(

There are probably differences between browsers and OS'es too...
So i tried Chrome: that works fine!!!

The keytest page shows Chrome sends keyCode 222 to Javascript for the single quote dead key, so its not 'dead' any more...

I don't think there is a solution to this.... frustrating i can type quotes here, in a textbox, in Firefox easily...

For me, i'll use Chrome as workaround. I don't see a fix for firefox.... So think we should just close this unless anybody has some bright ideas.

Great project btw, this WebMSX!

**Comment by ppeccin** [comment]
Yes, that is a problem of your OS + Browser combination not sending the correct key codes to Javascript.
Its a low-level key reporting bug.... There is not much we can do about this, besides mapping to other keys.

Or... Use a browser that works!  ;-)
Chrome is the best choice in my opinion. It's faster than Fire Fox for very intensive processing apps, and tends to work better in those kind of low-level specs.

Thanks!

**Comment by digitalica** [comment]
i'll go to Chrome. Think we can close this.

**Comment by ppeccin** [comment]
Please test it, and let me know if it works.

**Comment by digitalica** [comment]
i did. evertything is fine in chrome. So i'll just use Chrome ;-)

**Comment by ppeccin** [comment]
Good to know! Nice choice! :-)
