### ISSUE TITLE
how can i add new machine to CONFIG_URL ?

### ISSUE THREAD

**Issue by walaayakoot** [ppeccin/WebMSX#86]
how can i add new machine to CONFIG_URL ?
i have some arabic roms which runs on alalmiah ax-370 or ax-230 but iam not sure how to add this machine to CONFIG_URL
thanks

**Comment by ppeccin** [comment]
Hi.

It's not so simple, you have to provide and set each of the ROMs in the
correct slots, among other things.

But I have made an example config for you, please go to:
https://webmsx.org/?config_url=custom/machines.json

This config has 2 new machines that you can choose from normally from the
menu.
You can download the config file (the json file) and look at the contents.
All the ROMs in this example config also are located in the "custom" folder.

Regards,
Paulo
