### ISSUE TITLE
realfun3 missing vocals

### ISSUE THREAD

**Issue by denjhang** [ppeccin/WebMSX#93]
https://www.youtube.com/watch?v=JWkUhC7vnHw
When I play hunt, the vocal on scc channel 1 is completely gone.But it is normal in the youtube video.
https://github.com/openMSX/openMSX/files/10704978/realfun3_hunt.zip

**Comment by ppeccin** [comment]
How did you run it?
I'm trying to boot the disk in Nextor on WebMSX but it does not load.

Paulo

**Comment by denjhang** [comment]
I found out that it's just that I can't use realfun3 and the vocals don't appear, so it's not a webmsx problem.
Here is a connection, open it and run realfun3 directly without any settings
https://www.file-hunter.com/Homebrew/index.php?id=realfun3

**Comment by ppeccin** [comment]
Yes, I was able to load it and play Hunt normally.
Closing this issue.

Regards
