### ISSUE TITLE
Video9000: programmatically activate superimpose 

### ISSUE THREAD

**Issue by pvmm** [ppeccin/WebMSX#96]
Video9000 graphics cartridge does superimpose by itself if you use

```
OUT (0x6f), 0x18
```
to make it opaque and
```
OUT (0x6f), 0x10
```
to make it transparent. How about using this setting to superimpose automatically, instead of trying to detect it by used registers? This is how OpenMSX does it if you use the Video9000 extension.

**Comment by ppeccin** [comment]
Hi!

Can you link some specs please?

Regards,
Paulo

**Comment by pvmm** [comment]
Sure. It's on chapter 5 of the Video9000 manual: http://www.msxarchive.nl/pub/msx/mirrors/msx2.com/kiwi/hardware/pdf/Sunrise/v9manual.pdf

**Comment by ppeccin** [comment]
Thanks!

I'll have to check that, but as I remender I implemented those ports.
Isn't it working? Can you point me to some software that tries to activate
the modes in thi way but fails?

Paulo

**Comment by pvmm** [comment]
I fixed it on my side.
